### ISSUE TITLE
skips download

### ISSUE THREAD

**Issue by FruitsAndVegetables** [Incredibleflamer/Anime-batch-downloader-gui#1]
When downloading in a batch, it skips every other episode in the queue. For example, when I attempt to download episodes 1-12, only episodes 1, 3, 5, 7, 9, and 11 are downloaded.

**Comment by Incredibleflamer** [comment]
hey sorry about that! can you tell me the series name you were downloading, so i cross check and try to fix it asap

**Comment by FruitsAndVegetables** [comment]
i only tried 2 Seasons of Boku no Kokoro no Yabai Yatsu (Dangers in my Heart) and Lv2 kara Cheat datta Moto Yuusha Kouho no Mattari Isekai Life

**Comment by Incredibleflamer** [comment]
Thank you to @FruitsAndVegetables for pointing out the issue! It was indeed a bug, and I have now fixed it. Downloads should work perfectly. If you have any suggestions or further feedback, please let me know!

**Comment by Incredibleflamer** [comment]
Thank you @FruitsAndVegetables for pointing out the issue! It was indeed a bug, and I have now fixed it. Downloads should work perfectly. If you have any suggestions or further feedback, please let me know!

**Comment by bobothegamedev** [comment]
Projects like these are what inspire me to be a programmer. Just started learning to program 2 weeks ago and i doubt ill be able to make anything like it any time soon but, hope I will eventually. Thanks for the tool!
