### ISSUE TITLE
No Subbed in Zoro & no Subtitles showing in subtitles file

### ISSUE THREAD

**Issue by ECX-0** [Incredibleflamer/Anime-batch-downloader-gui#10]
Merge subtitles is off and I tested it on chainsaw man, cells at work, and patema inverted. Whenever downloading subbed, it downloads the dubbed version and the subtitles don't appear in the subtitles folder that appears.

**Comment by Incredibleflamer** [comment]
Thanks for pointing this out! I found the issue that was causing the dubbed version to download instead of the subbed one. It’s fixed now, and I’ll be rolling out an updated version soon. Thank you! 💓
