### ISSUE TITLE
It gets stuck after downloading 1 episode.

### ISSUE THREAD

**Issue by rifatozkancomtr** [Incredibleflamer/Anime-batch-downloader-gui#12]
![image](https://github.com/user-attachments/assets/60a1c07c-351b-447a-bfea-2e8d57fe3f52)

It works with VPN.!
Can you give me the source for Zoro? I want to redirect with controld.

Could the source be blocking it, for example Cloudflare?

When I close and open the program, another episode downloads and gets stuck.

![image](https://github.com/user-attachments/assets/ac4c7ffc-e03f-4012-9282-a8cd81dae080)

**Comment by Incredibleflamer** [comment]
you got discord?

**Comment by rifatozkancomtr** [comment]
> you got discord?
When you say discord, do you mean a discord account?
constantly gets stuck.

![image](https://github.com/user-attachments/assets/a418ae2d-60d0-480d-b34a-e9c79cfcacdf)

**Comment by Incredibleflamer** [comment]
add me on discord tag : neko.womp.womp i can help u there cuz idk what controld is

**Comment by rifatozkancomtr** [comment]
> add me on discord tag : neko.womp.womp i can help u there cuz idk what controld is

![image](https://github.com/user-attachments/assets/1d238880-f6c5-4cc9-80f2-304a3b1a3664)
I guess I'm a newbie in discord, I wrote.
