### ISSUE TITLE
Implement running in background

### ISSUE THREAD

**Issue by nath-277** [Incredibleflamer/Anime-batch-downloader-gui#13]
Nice app by the way
I suggest adding a feature to allow the app to run in the background

**Comment by Incredibleflamer** [comment]
background as in? like for what purpose?

**Comment by nath-277** [comment]
So i can close the app
Like you anit-virus
You close it  but it still runs in the background
i want it to be able to keep on downloading while not being open
Something like minimise to system tray

**Comment by Incredibleflamer** [comment]
The issue with implementing running in background, app will still use system resources even when it’s not actively downloading. and more over it can consume unnecessary system resources. 

However, you can simply minimize the app when you're downloading, and once you’re done, just close it 😄
