### ISSUE TITLE
Question: Title feature

### ISSUE THREAD

**Issue by AmarilloNL** [Incredibleflamer/Anime-batch-downloader-gui#2]
Is there a way to export episodes with their full anime name in it + episode number?  Now it only shows the episode number.

**Comment by Incredibleflamer** [comment]
I don’t think so. Gogo doesn’t store anime episodes names, it just stores episode numbers along with the anime title, for example: isekai-shikkaku-episode-4. 😔

**Comment by AmarilloNL** [comment]
Loud and clear. Thank you for your responds and thank you for the awesome tool you made!
