### ISSUE TITLE
Not donwloading some episodes

### ISSUE THREAD

**Issue by dragnslayer202** [Incredibleflamer/Anime-batch-downloader-gui#5]
When im downloading, It downloads one episode, then skips one, then downloads the next one, but skips the next one. This keeps on happening, and I have to manually install the episodes it skips, and it skips some of those too.

**Comment by Incredibleflamer** [comment]
hey you maybe using old version 
https://github.com/Incredibleflamer/Anime-batch-downloader-gui/releases/tag/v1.0.0.1

**Comment by dragnslayer202** [comment]
alr thanks
