### ISSUE TITLE
virus 1/65 on all of the 3 versions

### ISSUE THREAD

**Issue by Antinightcurse** [Incredibleflamer/Anime-batch-downloader-gui#6]
virustotal is saying all 3 have a virus for [v1.0.0.1],[v1.0.0.2],[v2.0.0.0], it only says 1/65 but still, the old version i have has 0/65 just letting you know.

**Comment by Antinightcurse** [comment]
![image_2024-10-12_165001876](https://github.com/user-attachments/assets/abc0f6c9-d060-454b-a2a9-b9fcdff551c0)

**Comment by Incredibleflamer** [comment]
To be brutally honest, I believe this is likely a false detection, or perhaps some module hasn't been updated yet.

**Comment by Incredibleflamer** [comment]
W32.AIDetectMalware is a very common false positive that may appear on a VirusTotal scan

https://hackerdose.com/malware/w32-aidetectmalware-bkav-pro/

**Comment by Antinightcurse** [comment]
> W32.AIDetectMalware is a very common false positive that may appear on a VirusTotal scan
> 
> https://hackerdose.com/malware/w32-aidetectmalware-bkav-pro/

I knew there was a chance of it being a false positive, however do you know what could be the problem with all 3 of the versions, also great work with making this project I really appreciate you making this and responding to me!

**Comment by Incredibleflamer** [comment]
no clew i tried to debug from my end as well still no luck in new update 😢
