### ISSUE TITLE
Can I download the subtitle files separately?

### ISSUE THREAD

**Issue by rifatozkancomtr** [Incredibleflamer/Anime-batch-downloader-gui#8]
Can I download the subtitle files separately?

**Comment by Incredibleflamer** [comment]
i dont think so , its combined from gogo

**Comment by rifatozkancomtr** [comment]
> i dont think so , its combined from gogo

This news is very sad

**Comment by Incredibleflamer** [comment]
now you can! [download](https://github.com/Incredibleflamer/Anime-batch-downloader-gui/releases/tag/v2.0.0.4) this latest release, go to setting and change provider to zoro and make sure mergeSubtitles is off
